@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.lalaalal.yummy.networking;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;